# Generated by Django 5.1.1 on 2024-09-08 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alimentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                ("dosis", models.TextField(verbose_name="Dosis")),
            ],
            options={
                "verbose_name": "Alimentacion",
                "verbose_name_plural": "Alimentaciones",
                "db_table": "Alimentacion",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cedula",
                    models.CharField(max_length=50, unique=True, verbose_name="Cedula"),
                ),
                ("nombres", models.CharField(max_length=200, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=400, verbose_name="Apellidos"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=500, verbose_name="Dirección"),
                ),
                ("telefono", models.CharField(max_length=20, verbose_name="Teléfono")),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clientes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Porcino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raza", models.CharField(max_length=50, verbose_name="Raza")),
                ("edad", models.PositiveSmallIntegerField(verbose_name="Edad")),
                ("peso", models.FloatField(verbose_name="Peso")),
                (
                    "alimentacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LaGranja.alimentacion",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LaGranja.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Porcino",
                "verbose_name_plural": "Porcinos",
                "db_table": "porcinos",
                "ordering": ["id"],
            },
        ),
    ]
